# Generated by Django 3.2.3 on 2021-05-29 11:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField()),
                ('keywords', models.CharField(max_length=200)),
                ('publish_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
