# Generated by Django 3.2.3 on 2021-05-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0002_auto_20210529_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
