# Generated by Django 3.2.3 on 2021-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0003_blogs_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug_field',
            field=models.SlugField(default='slug'),
        ),
    ]
