# Generated by Django 3.2.3 on 2021-05-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0004_blogs_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
