# Generated by Django 3.2.3 on 2021-05-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0014_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
