# Generated by Django 3.2.3 on 2021-05-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0015_remove_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
