# Generated by Django 3.2.3 on 2021-05-30 15:05

import ckeditor.fields
from django.db import migrations, models
import project_blogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_blogs', '0016_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug_field', models.SlugField(default='slug')),
                ('description', models.TextField(default='description')),
                ('image', models.ImageField(null=True, upload_to=project_blogs.models.upload_image_path)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('seo_meta', models.TextField(default='seo meta')),
                ('keywords', models.CharField(max_length=200, null=True)),
                ('show', models.BooleanField(default=False)),
                ('publish_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
