# Generated by Django 3.2.3 on 2021-05-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_blogs', '0020_alter_blogs_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='project_blogs.category'),
        ),
    ]
