# Generated by Django 3.2.3 on 2021-05-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
