# Generated by Django 3.2.3 on 2021-05-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sliders', '0002_alter_slider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_url',
            field=models.URLField(),
        ),
    ]
