# Generated by Django 3.2.3 on 2021-05-19 14:33

from django.db import migrations, models
import project_sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sliders', '0003_alter_slider_button_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to=project_sliders.models.upload_image_path),
        ),
    ]
