# Generated by Django 3.2.3 on 2021-05-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_sliders', '0005_rename_image_slider_image_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image_slider',
            new_name='image',
        ),
    ]
