# Generated by Django 3.2.3 on 2021-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sliders', '0007_alter_slider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image',
        ),
        migrations.AddField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
