# Generated by Django 3.2.3 on 2021-05-19 15:55

from django.db import migrations, models
import project_sliders.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_sliders', '0008_auto_20210519_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to=project_sliders.models.upload_image_path),
        ),
    ]
